name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  confetti: ^0.7.0
  
  pdf: ^3.11.0
  printing: ^5.13.1

  flutter_local_notifications: ^17.1.2
  
  # UI and Icons
  cupertino_icons: ^1.0.8

  # Firebase dependencies
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0

  # Utilities
  intl: ^0.20.2
  uuid: ^4.5.1
  fl_chart: ^0.68.0
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  lottie: ^3.3.2

  # Animation + Fonts (added for Dashboard UI)
  google_fonts: ^6.3.2
  animate_do: ^3.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/animations/subtrack.json
    - assets/logo.png   

flutter_launcher_icons:
  android: true
  ios: true

  image_path: "assets/logo.png"

  # iOS uses flat PNG
  image_path_ios: "assets/logo.png"

  # Android adaptive icons (for full circle fill)
  android_adaptive_icon_foreground: "assets/logo_foreground.png"
  android_adaptive_icon_background: "assets/logo_background.png"
